Django/myblog/blog/urls.py
from django.urls import path,re_path
from django.conf.urls import url
from . import views

urlpatterns = [
    path('index/', views.index),
    #path('page/',  views.article_page1),
    #re_path(r'^page/(?P<article_id>[0-9]+)', views.article_page)
    re_path(r'^page/(?P<article_id>[0-9]+)/$', views.article_page,name='page'),
    re_path(r'^edit/(?P<article_id>[0-9]+)/$',views.edit_page,name='edit_page'),
    re_path(r'^edit/action/$',views.edit_action,name='edit_action'),
]


Django/myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'blog/',include(('blog.urls','blog'),namespace='blog')),
    # path(r'blog/',include('blog.urls')),
]

Django/myblog/blog/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=32,default="Title")
    content = models.TextField(null=True)
    pub_time =models.DateTimeField(null=True)
    def __str__(self):
        return self.title
    # def __unicode__(self):
    #     return self.title

Django/myblog/blog/views.py
from django.shortcuts import render
#from django.http import  HttpResponse
from . import models
# Create your views here.

def index(request):
    #article = models.Article.objects.get(pk=1)
    articles = models.Article.objects.all()
    return render(request,'blog/index.html',{'articles':articles})
def article_page(request,article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request,'blog/page.html',{'article':article})
def edit_page(request,article_id):
    if str(article_id) == '0':
        return render(request,'blog/edit_page.html')
    else:
        article = models.Article.objects.get(pk=article_id)
        return render(request, 'blog/edit_page.html',{'article':article})
def edit_action(request):
    title = request.POST.get('title','TITLE')
    content = request.POST.get('content','CONTENT')
    article_id = request.POST.get('article_id','0')
    if article_id == '0':
        models.Article.objects.create(title=title,content=content)
        articles = models.Article.objects.all()
        return render(request, 'blog/index.html', {'articles': articles})
    else:
        article = models.Article.objects.get(pk=article_id)
        article.title = title
        article.content = content
        article.save()
        return render(request, 'blog/page.html', {'article': article})

Django/myblog/blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Page</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}"method="post">
    {% csrf_token %} {#POST防止报错#}
    <input type="hidden" name="article_id" value="{{ article.id | default:'0' }}"/>
    <label>文章标题
    <input type="text" name="title" value="{{ article.title }}"/>
        </label>
    <br/>
    <label>文章内容
    <input  style="width:200px; height: 300px" type="text" name="content" value="{{ article.content }}"/>
        </label>
    <br/>
    <input  type="submit" value="确定"/>
</form>
</body>
</html>

Django/myblog/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>hello,blog</title>
</head>
<body>
<h1>
    <a href ="{% url 'blog:edit_page' 0%}">新文章</a>
</h1>
{% for article in articles %}
    <a href="{% url 'blog:page' article.id %}">{{ article.title}}</a>
    <h3>{{article.id }}/{{article.title}}/{{article.content}}</h3>
    <br/>
{% endfor %}
</body>
</html>

Django/myblog/blog/templates/blog/page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{article.title}}</title>
</head>
<body>
<h1>{{article.title}}</h1>
<h3>{{article.content}}</h3>
<br/><br/>
<a href="{% url 'blog:edit_page' article.id  %}">修改文章</a>
</body>
</html>